fix(Apple): Fix tests depending on ReactTestApp-DevSupport not building (#181)
The symbols declared in ReactTestApp-DevSupport aren't compiled in the
same module, but in the main ReactTestApp module. This causes tests to
fail building because the linker cannot find the symbols, e.g.:

```
Undefined symbols for architecture x86_64:
  "_ReactTestAppSceneDidOpenURLNotification", referenced from:
      -[ADALTokenBroker init] in libReactTestApp-Contoso.a(ADALTokenBroker.o)
  "_ReactTestAppDidInitializeNotification", referenced from:
      +[ADALTokenBroker load] in libReactTestApp-Contoso.a(ADALTokenBroker.o)
      +[ReactBootstrapper load] in libReactTestApp-Contoso.a(ReactBootstrapper.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```