fix(apple): fix `ReactTestApp_DevSupport` missing bridging header
Addresses this non-fatal build error:

```
fatal error: module 'ReactTestApp_DevSupport' in AST file [...] is not
defined in any loaded module map file; maybe you need to load
'/~/macos/Pods/Headers/Public/ReactTestApp_DevSupport/ReactTestApp-DevSupport.modulemap'?
```