chore: pin Flipper-RSocket version to fix iOS nightly builds (#336)
iOS nightly builds are failing due to `Flipper-RSocket` being resolved
to a version that depends on a newer version of `Flipper-Folly`:

```
[!] CocoaPods could not find compatible versions for pod "Flipper-Folly":
  In snapshot (Podfile.lock):
    Flipper-Folly (= 2.5.3, ~> 2.5)

  In Podfile:
    Flipper-Folly (= 2.5.3)

    Flipper-RSocket (= 1.4.3) was resolved to 1.4.3, which depends on
      Flipper-Folly (~> 2.6)

    FlipperKit/FlipperKitLayoutPlugin (= 0.75.1) was resolved to 0.75.1, which depends on
      FlipperKit/Core (= 0.75.1) was resolved to 0.75.1, which depends on
        Flipper (~> 0.75.1) was resolved to 0.75.1, which depends on
          Flipper-Folly (~> 2.5)
Error: Process completed with exit code 1.
```